import { DataSource } from 'typeorm';
import { Activity } from 'src/entities/Activity';

export async function seedActivities(dataSource: DataSource) {
  const repo = dataSource.getRepository(Activity);
  const activitiesSeed = [
    {
      name: 'Sea Kayaking',
      activityType: 'Parasailing',
      pricePerHour: 475.66,
      createdAt: '2025-02-10T16:29:42',
      updatedAt: '2025-03-30T20:34:31',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,0',
      destinationId: 1,
      minAge: 15,
      rating: 3.7,
      reviewCount: 48,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description:
        'Pretty way property decide item people hand art finish evidence alone rather.',
    },
    {
      name: 'Skill Parasailing',
      activityType: 'Scuba Diving',
      pricePerHour: 462.15,
      createdAt: '2025-04-01T10:50:14',
      updatedAt: '2025-01-31T08:26:18',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,1',
      destinationId: 1,
      minAge: 7,
      rating: 3.9,
      reviewCount: 90,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description:
        'Suggest beat behavior door window question black anyone outside.',
    },
    {
      name: 'Message Scuba Diving',
      activityType: 'Parasailing',
      pricePerHour: 553.83,
      createdAt: '2025-05-08T14:07:57',
      updatedAt: '2025-04-14T18:34:06',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,2',
      destinationId: 1,
      minAge: 18,
      rating: 4.5,
      reviewCount: 87,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description: 'Technology born research base wish newspaper.',
    },
    {
      name: 'Garden Jet Ski',
      activityType: 'Snorkeling',
      pricePerHour: 835.03,
      createdAt: '2025-02-16T22:20:41',
      updatedAt: '2025-05-13T08:10:04',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,3',
      destinationId: 1,
      minAge: 10,
      rating: 4.5,
      reviewCount: 81,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description: 'Well office environment cost would fire senior bank.',
    },
    {
      name: 'Pretty Snorkeling',
      activityType: 'Scuba Diving',
      pricePerHour: 761.68,
      createdAt: '2025-04-14T08:55:00',
      updatedAt: '2025-03-30T01:23:40',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,4',
      destinationId: 1,
      minAge: 10,
      rating: 4.2,
      reviewCount: 182,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description: 'Shoulder chair business main soldier rather.',
    },
    {
      name: 'Present Kayaking',
      activityType: 'Snorkeling',
      pricePerHour: 788.93,
      createdAt: '2025-04-28T13:40:07',
      updatedAt: '2025-02-23T14:33:56',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,5',
      destinationId: 2,
      minAge: 6,
      rating: 4.6,
      reviewCount: 151,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description: 'Card simply record reduce pattern create current.',
    },
    {
      name: 'Range Kayaking',
      activityType: 'Parasailing',
      pricePerHour: 807.13,
      createdAt: '2025-01-13T11:38:11',
      updatedAt: '2025-03-28T02:24:45',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,6',
      destinationId: 2,
      minAge: 16,
      rating: 3.9,
      reviewCount: 99,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description:
        'Rate mind my single light determine economic any capital process local.',
    },
    {
      name: 'Collection Snorkeling',
      activityType: 'Snorkeling',
      pricePerHour: 399.89,
      createdAt: '2025-01-26T01:09:28',
      updatedAt: '2025-02-13T17:11:15',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,7',
      destinationId: 2,
      minAge: 12,
      rating: 4.3,
      reviewCount: 49,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description:
        'Today continue indeed reality foreign open participant according company month my.',
    },
    {
      name: 'Model Scuba Diving',
      activityType: 'Parasailing',
      pricePerHour: 463.7,
      createdAt: '2025-05-06T11:41:56',
      updatedAt: '2025-05-18T20:28:58',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,8',
      destinationId: 2,
      minAge: 13,
      rating: 3.8,
      reviewCount: 46,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description:
        'Dream economic before other sit capital thousand after call several not machine.',
    },
    {
      name: 'Buy Snorkeling',
      activityType: 'Kayaking',
      pricePerHour: 851.7,
      createdAt: '2025-04-19T01:52:50',
      updatedAt: '2025-03-01T06:48:39',
      deletedAt: null,
      pics: 'https://source.unsplash.com/800x600/?activity,water,sports,9',
      destinationId: 2,
      minAge: 6,
      rating: 4.7,
      reviewCount: 127,
      durationOptions: ['30', '60', '90'],
      durationUnit: 15,
      description: 'Serve rule hundred buy she us yeah such film last on kind.',
    },
  ];
  await repo.save(activitiesSeed);
  console.log('✅ Activities seeded');
}
